server:
  port: 7018
spring:
  application:
    name: auth
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://cx/gusteau-cv?useUnicode=true&characterEncoding=UTF-8&failOverReadOnly=false&autoReconnect=true&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    username: xxx
    password: xxx
  devtools:
    add-properties: false

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: net.xinhuamm.auth.domain.*


eureka:
  instance:
    app-group-name: "认证中心"
    appname: "认证中心"
    prefer-ip-address: true
    #健康心跳时间
    lease-renewal-interval-in-seconds: 10
    #最长剔除时间
    lease-expiration-duration-in-seconds: 20
  client:
    registerWithEureka: true #是否向服务注册中心注册自己
    fetchRegistry: true #是否检索服务
    serviceUrl: #服务注册中心的配置内容，指定服务注册中心的位置
      defaultZone: http://10.0.0.63:7003/eureka/
    healthcheck:
      enabled: false
